### ISSUE TITLE
mk_media_start_send_rtp会崩溃！

### ISSUE THREAD

**Issue by xinsuinizhuan** [mingyuejingque/zlm_test#1]
![图片](https://user-images.githubusercontent.com/40679769/197564485-d171bf6f-8fad-4bc0-acd2-b3137ba31064.png)
![图片](https://user-images.githubusercontent.com/40679769/197564542-0608b3fa-34fa-4dab-bc9b-b6136e83cc47.png)

**Comment by mingyuejingque** [comment]
https://github.com/ZLMediaKit/ZLMediaKit/issues/2058
