### ISSUE TITLE
请问，启动后，访问地址是什么？

### ISSUE THREAD

**Issue by xinsuinizhuan** [mingyuejingque/zlm_test#2]
我使用rtsp://127.0.0.1:30443/live/zlm_test请求不到数据，没法播放

另外：
 ctx = mk_media_create("__defaultVhost__", "live", "zlm_test", 0, 0, true);
和
    mk_media_start_send_rtp(
        g_ctx.zlm, "127.0.0.1", 30443, g_ctx.stream_name, true, dz_on_mk_media_source_send_rtp_result, nullptr);
分别是什么意思？
在我理解，应该是创建一个媒体源，直接是一个播放地址即可，但是，这两个没看懂啥意思，并且地址播放不了

**Comment by mingyuejingque** [comment]
https://github.com/ZLMediaKit/ZLMediaKit/issues/2058
